language: python
python:
  - "2.7"
  - "3.5"
addons:
  firefox: "53.0"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install: 
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.16.0/geckodriver-v0.16.0-linux64.tar.gz
  - mkdir geckodriver && tar zxvf geckodriver-v0.16.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver
install: "pip install -r requirements.txt"
script: sh test.sh